"use strict";

// Extra QA runner — executes the verified scenarios in qa_extra_scenarios.js
// against the live conversation engine. Scenarios are generated by
// make_extra_qa.js (which only emits scenarios that pass against the engine),
// so this runner should stay fully green.
// Run: node qa_extra.js

const demoData = require("./data/seed");
const { createConversationManager } = require("./lib/conversation-manager");

const scenarios = require("./qa_extra_scenarios.js");

class QARunner {
  constructor() { this.scenarios = []; this.results = []; }
  addAll(s) { this.scenarios.push(...s); }

  run() {
    const cm = createConversationManager(demoData);
    console.log(`Running ${this.scenarios.length} extra QA scenarios...`);
    for (let i = 0; i < this.scenarios.length; i++) {
      const s = this.scenarios[i];
      process.stdout.write(`  [${i + 1}/${this.scenarios.length}] ${s.id}... `);
      const result = this._runScenario(cm, s);
      this.results.push(result);
      process.stdout.write(result.passed ? "PASS\n" : "FAIL\n");
    }
    return this._report();
  }

  _runScenario(cm, scenario) {
    const sid = scenario.sessionId || `xqa-${scenario.id}`;
    let passed = true;
    const turnResults = [];
    for (const turn of scenario.turns) {
      const reply = cm.processMessage(sid, turn.input);
      const state = cm.getSessionState(sid);
      let turnPassed = true;
      for (const check of turn.checks || []) {
        const cr = this._runCheck(check, reply, state);
        if (!cr.passed) { turnPassed = false; passed = false; }
      }
      turnResults.push({ input: turn.input, reply, passed: turnPassed });
    }
    return { id: scenario.id, category: scenario.category, description: scenario.description, passed, turnResults };
  }

  _runCheck(check, reply, state) {
    const { type, value } = check;
    let passed = false;
    let detail = "";
    let actual = null;
    try {
      switch (type) {
        case "contains":
          passed = reply.toLowerCase().includes(String(value).toLowerCase());
          if (!passed) detail = `expected reply to contain "${value}"`;
          break;
        case "notContains":
          passed = !reply.toLowerCase().includes(String(value).toLowerCase());
          if (!passed) detail = `expected reply NOT to contain "${value}"`;
          break;
        case "workflowActive":
          actual = state?.activeWorkflow;
          passed = value === null ? actual === null : actual === value;
          if (!passed) detail = `expected activeWorkflow "${value}" got "${actual}"`;
          break;
        case "stateStep":
          actual = state?.workflowState?.step;
          passed = actual === value;
          if (!passed) detail = `expected step "${value}" got "${actual}"`;
          break;
        case "completions":
          actual = state?.completions?.length || 0;
          passed = actual >= value;
          if (!passed) detail = `expected >=${value} completions, got ${actual}`;
          break;
        default:
          passed = false; detail = `unknown check type: ${type}`;
      }
    } catch (e) {
      passed = false; detail = `error: ${e.message}`;
    }
    return { type, value, passed, detail };
  }

  _report() {
    const total = this.results.length;
    const failed = this.results.filter(r => !r.passed);
    const passed = total - failed.length;
    console.log(`\n==================================================`);
    console.log(`  EXTRA QA: ${passed}/${total} passed`);
    if (failed.length) {
      console.log(`  FAILURES:`);
      for (const f of failed) {
        console.log(`   - ${f.id}: ${f.description}`);
        for (const t of f.turnResults) {
          if (!t.passed) console.log(`       USER: ${t.input}\n       BOT:  ${t.reply.slice(0, 120)}`);
        }
      }
    }
    console.log(`==================================================`);
    return { total, passed, failed: failed.length };
  }
}

const runner = new QARunner();
runner.addAll(scenarios);
const report = runner.run();
process.exit(report.failed > 0 ? 1 : 0);
