export const ErrorCodes = {
  // Stage 1 — CONVERSATION_ENGINE.md, SAFETY.md, MESSAGING_AND_CONSISTENCY.md
  ERR_AUTH_INVALID_KEY: 'ERR_AUTH_INVALID_KEY',
  ERR_AUTH_TENANT_DEACTIVATED: 'ERR_AUTH_TENANT_DEACTIVATED',
  ERR_TENANT_NOT_FOUND: 'ERR_TENANT_NOT_FOUND',
  ERR_TENANT_REGISTRY_UNAVAILABLE: 'ERR_TENANT_REGISTRY_UNAVAILABLE',
  ERR_RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',
  ERR_OUT_OF_SEQUENCE: 'ERR_OUT_OF_SEQUENCE',
  ERR_DEDUP_DETECTED: 'ERR_DEDUP_DETECTED',
  ERR_CRISIS_DETECTED: 'ERR_CRISIS_DETECTED',
  ERR_INPUT_GUARDRAIL: 'ERR_INPUT_GUARDRAIL',
  ERR_PII_DETECTED: 'ERR_PII_DETECTED',
  ERR_INJECTION_DETECTED: 'ERR_INJECTION_DETECTED',

  // Stage 2 — TENANT_ISOLATION.md
  ERR_CONFIG_VERSION_NOT_FOUND: 'ERR_CONFIG_VERSION_NOT_FOUND',
  ERR_CONFIG_CORRUPT: 'ERR_CONFIG_CORRUPT',
  ERR_CONFIG_STORE_UNREACHABLE: 'ERR_CONFIG_STORE_UNREACHABLE',

  // Stage 5 — Response Generation
  ERR_LLM_TIMEOUT: 'ERR_LLM_TIMEOUT',
  ERR_LLM_INFERENCE_FAILURE: 'ERR_LLM_INFERENCE_FAILURE',
  ERR_LLM_OVERLOADED: 'ERR_LLM_OVERLOADED',
  ERR_LLM_PROVIDER_UNAVAILABLE: 'ERR_LLM_PROVIDER_UNAVAILABLE',
  ERR_CONTEXT_TOO_LARGE: 'ERR_CONTEXT_TOO_LARGE',

  // Stage 6a — SAFETY.md
  ERR_SAFETY_GATE: 'ERR_SAFETY_GATE',
  ERR_OUTPUT_GUARDRAIL: 'ERR_OUTPUT_GUARDRAIL',
  ERR_GROUNDING_FAILED: 'ERR_GROUNDING_FAILED',

  // Stage 7 — SESSION_AND_PERSISTENCE.md
  ERR_SESSION_VERSION_CONFLICT: 'ERR_SESSION_VERSION_CONFLICT',
  ERR_SESSION_STORE_UNAVAILABLE: 'ERR_SESSION_STORE_UNAVAILABLE',

  // Stage 8 — CONVERSATION_ENGINE.md
  ERR_RESPONSE_TOO_LARGE: 'ERR_RESPONSE_TOO_LARGE',

  // Downstream — DOWNSTREAM_INTEGRATION.md
  ERR_CREDENTIALS_NOT_FOUND: 'ERR_CREDENTIALS_NOT_FOUND',
  ERR_ADAPTER_UNAVAILABLE: 'ERR_ADAPTER_UNAVAILABLE',
  ERR_ADAPTER_TIMEOUT: 'ERR_ADAPTER_TIMEOUT',

  // General — FAILURE_AND_RECOVERY.md
  ERR_STAGE_TIMEOUT: 'ERR_STAGE_TIMEOUT',
  ERR_INTERNAL: 'ERR_INTERNAL',

  // Security — SECURITY.md
  ERR_SECRETS_VAULT_UNREACHABLE: 'ERR_SECRETS_VAULT_UNREACHABLE',
  ERR_SECRET_MISSING: 'ERR_SECRET_MISSING',
  ERR_CERT_INVALID: 'ERR_CERT_INVALID',
  ERR_AUTH_PROVIDER_UNREACHABLE: 'ERR_AUTH_PROVIDER_UNREACHABLE',
  ERR_FORBIDDEN: 'ERR_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
