import {
  Bot,
  Braces,
  Calculator,
  CaseSensitive,
  ClipboardList,
  Code,
  Cog,
  Copy,
  FileCode2,
  FileInput,
  FileJson,
  FileOutput,
  FileText,
  FolderTree,
  GitCompare,
  Globe,
  Library,
  Link,
  ListChecks,
  Mail,
  Merge,
  MessagesSquare,
  PenLine,
  PieChart,
  ScanLine,
  Search,
  Shield,
  Sparkles,
  Table,
  TextQuote,
  Type,
  Wand2,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  bot: Bot,
  braces: Braces,
  calculator: Calculator,
  'case-sensitive': CaseSensitive,
  'clipboard-list': ClipboardList,
  code: Code,
  cog: Cog,
  copy: Copy,
  'file-code-2': FileCode2,
  'file-input': FileInput,
  'file-json': FileJson,
  'file-output': FileOutput,
  'file-text': FileText,
  'folder-tree': FolderTree,
  'git-compare': GitCompare,
  globe: Globe,
  library: Library,
  link: Link,
  'list-checks': ListChecks,
  mail: Mail,
  merge: Merge,
  'messages-square': MessagesSquare,
  'pen-line': PenLine,
  'pie-chart': PieChart,
  'scan-line': ScanLine,
  search: Search,
  shield: Shield,
  sparkles: Sparkles,
  table: Table,
  'text-quote': TextQuote,
  type: Type,
  'wand-2': Wand2,
  zap: Zap,
};

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name] ?? Sparkles;
  return <Icon className={className} aria-hidden="true" />;
}